version: '3'

services:
  web:
    build: ./
    image: "aicloudalbum:latest"
    container_name: "aicloudalbum"
    ports:
      - "9193:9193"
    expose:
      - "9193"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    depends_on:
      - web
    links:
      - web
#  supervisor:
#    build:
#      context: .
#    command:
#      - bash -c "supervisord"
#      - bash -c "supervisorctl start daphne"
#    depends_on:
#      - python
#      - nginx
#    ports:
#      - "9191:9191"
#    expose:
#      - "9191"

